[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs

lib_deps =
    adafruit/Adafruit BMP280 Library
    adafruit/Adafruit Unified Sensor
    bblanchon/ArduinoJson@^7.0.0
